### ISSUE TITLE
[BUG] mac m1 docker部署 运行无法连接 kafka

### ISSUE THREAD

**Issue by ltsj404** [OpenIMSDK/Open-IM-Server#104]
```base
[GIN-debug] Listening and serving HTTP on 0.0.0.0:10000
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
Open_IM/pkg/common/kafka.NewKafkaProducer({0xc00006b790, 0x1, 0x1}, {0xc0000368d0, 0xa})
	/Open-IM-Server/pkg/common/kafka/producer.go:28 +0x185
Open_IM/internal/push/logic.init.0()
	/Open-IM-Server/internal/push/logic/init.go:30 +0x3c
panic: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

goroutine 1 [running]:
Open_IM/pkg/common/kafka.NewKafkaProducer({0xc00010d730, 0x1, 0x1}, {0xc0001348a0, 0xa})
	/Open-IM-Server/pkg/common/kafka/producer.go:28 +0x185
Open_IM/internal/push/logic.init.0()
	/Open-IM-Server/internal/push/logic/init.go:30 +0x3c
RegisterEtcd
RegisterEtcd
RegisterEtcd
RegisterEtcd
RegisterEtcd
2021/12/12 17:34:59 [ open_im_sdk_init_login.go : 16 ] [InitOnce success,  {5 http://192.168.65.3:10000 ws://192.168.65.3:17778 ../db/sdk/}]
ws server is starting
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /auth/code                --> Open_IM/internal/demo/register.SendVerificationCode (4 handlers)
[GIN-debug] POST   /auth/verify              --> Open_IM/internal/demo/register.Verify (4 handlers)
[GIN-debug] POST   /auth/password            --> Open_IM/internal/demo/register.SetPassword (4 handlers)
[GIN-debug] POST   /auth/login               --> Open_IM/internal/demo/register.Login (4 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:42233


```

**Comment by ClockworkChen** [comment]
用ps -ef|grep kafka检查下kafka进程，然后用telnet或者nc命令查看kafka端口是否能连接。

**Comment by xyctruth** [comment]
我更新了一下docker-compose，我在我本机 mac 使用成功了。你可以尝试下。 #138

**Comment by ltsj404** [comment]
> 我更新了一下docker-compose，我在我本机 mac 使用成功了。你可以尝试下。 #138

好的，谢谢提醒
