### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by congxiaodan** [OpenIMSDK/Open-IM-Server#154]
```bash
[recv request from web:  reqFuncName  GetHistoryMessageList data  {"groupID":"9e8d883f383213d448ca13ec0a84702b","startClientMsgID":"","count":10,"userID":""} recv jsonMsg:  {"reqFuncName":"GetHistoryMessageList","operationID":"81vyf77cai1646291527305618441240","userID":"618441240","data":"{\"groupID\":\"9e8d883f383213d448ca13ec0a84702b\",\"startClientMsgID\":\"\",\"count\":10,\"userID\":\"\"}"}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa53ea6]

goroutine 7888 [running]:
open_im_sdk/internal/conversation_msg.(*Conversation).getHistoryMessageList(0x0, {0xdaf208, 0xc001290ab0}, {{0x0, 0x0}, {0xc0003d4420, 0x20}, {0x0, 0x0}, 0xa}, ...)
	/Open-IM-Server/cmd/Open-IM-SDK-Core/internal/conversation_msg/conversation.go:202 +0x126
open_im_sdk/internal/conversation_msg.(*Conversation).GetHistoryMessageList.func1()
	/Open-IM-Server/cmd/Open-IM-SDK-Core/internal/conversation_msg/open_im_sdk_conversation_msg.go:875 +0x19d
created by open_im_sdk/internal/conversation_msg.(*Conversation).GetHistoryMessageList
	/Open-IM-Server/cmd/Open-IM-SDK-Core/internal/conversation_msg/open_im_sdk_conversation_msg.go:871 +0x112
```

用户的 sqlite 中会话列表里面没有该群组的会话，直接获取群组历史记录必崩。
version: v2.0.1

**Comment by skiffer-git** [comment]
Waiting for new version
