### ISSUE TITLE
[BUG] 当 `offlinePushInfo` 为 `null` 时产生 10002 异常

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2987]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

当调用 `sendMessage` 并不传递 `offlinePushInfo` 值（或给 `null`）时，产生以下异常。

```
flutter: │ 🐛 ChatView,11:50:33.651:message send failed e :PlatformException(10002, unexpected end of JSON input, null, null)  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:646:7)
flutter: │ 🐛 #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
flutter: │ 🐛 <asynchronous suspension>
flutter: │ 🐛 #2      MessageManager.sendMessage.<anonymous closure> (package:flutter_openim_sdk/src/manager/im_message_manager.dart:53:17)
flutter: │ 🐛 <asynchronous suspension>
flutter: │ 🐛 #3      ChatLogic._sendMessage.<anonymous closure> (package:im/pages/chat/logic.dart:674:15)
flutter: │ 🐛 <asynchronous suspension>
flutter: │ 🐛 #4      ChatLogic._sendMessage.<anonymous closure> (package:im/pages/chat/logic.dart:679:20)
flutter: │ 🐛 <asynchronous suspension>
```

**Comment by cipchk** [comment]
另外一点所有 SDK 里面的 `offlinePushInfo` 发送消息接口都是必填，那么应该怎么处理群不推送离线消息呢？

**Comment by withchao** [comment]
Thanks for reaching out.

To configure this correctly, you need to include the offlinePushInfo parameter in your request. Please note that the final boolean parameter represents isOnlineOnly. When you set this parameter to true, the message will be treated strictly as an online-only message.

Let us know if you need any further assistance!
