### ISSUE TITLE
发送消息后报告异常。

### ISSUE THREAD

**Issue by smokesea** [OpenIMSDK/Open-IM-Server#59]
### 异常如下
另：发送消息需要先创建Conversation嘛
```
2021/11/11 15:52:39 [ ws_init_login.go : 158 ] [Conn is nil data {OnRecvNewMessage 0  {"clientMsgID":"bce95e482242b992c665fb48c2644dbf","serverMsgID":"2021-11-11 15:52:39-d5645454517-4037200794235010051","createTime":0,"sendTime":1636617159437581458,"sessionType":1,"sendID":"d5645454517","recvID":"d5645454518","msgFrom":100,"contentType":101,"platformID":5,"forceList":null,"senderNickName":"张三","senderFaceUrl":"https:oss.com.cn/head","groupID":"","content":"cdddddd","seq":20,"isRead":false,"status":2,"remark":"","pictureElem":{"sourcePath":"","sourcePicture":{"uuid":"","type":"","size":0,"width":0,"height":0,"url":""},"bigPicture":{"uuid":"","type":"","size":0,"width":0,"height":0,"url":""},"snapshotPicture":{"uuid":"","type":"","size":0,"width":0,"height":0,"url":""}},"soundElem":{"uuid":"","soundPath":"","sourceUrl":"","dataSize":0,"duration":0},"videoElem":{"videoPath":"","videoUUID":"","videoUrl":"","videoType":"","videoSize":0,"duration":0,"snapshotPath":"","snapshotUUID":"","snapshotSize":0,"snapshotUrl":"","snapshotWidth":0,"snapshotHeight":0},"fileElem":{"filePath":"","uuid":"","sourceUrl":"","fileName":"","fileSize":0},"mergeElem":{"title":"","abstractList":null,"multiMessage":null},"atElem":{"text":"","atUserList":null,"isAtSelf":false},"locationElem":{"description":"","longitude":0,"latitude":0},"customElem":{"data":"","description":"","extension":""},"quoteElem":{"text":"","quoteMessage":null}} 0} d5645454518]
[GIN] 2021/11/11 - 15:52:39 | 200 |    3.625433ms |     172.16.3.96 | POST     "/group/get_group_applicationList"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x500747]

goroutine 131 [running]:
database/sql.(*Rows).Next(0x0)
        /usr/local/go/src/database/sql/sql.go:2944 +0x27
open_im_sdk/open_im_sdk.(*UserRelated).getAllConversationListModel(0xfb78e0)
        /Open-IM-Server/src/Open-IM-SDK-Core/open_im_sdk/data_model.go:375 +0x105
open_im_sdk/open_im_sdk.(*UserRelated).doUpdateConversation(0xc0003ecb00, {{0x0, 0x9}, {0xa8e180, 0xc00046b970}})
        /Open-IM-Server/src/Open-IM-SDK-Core/open_im_sdk/conversation_msg.go:357 +0x62f
open_im_sdk/open_im_sdk.(*UserRelated).doMsgNew(0xc0003ecb00, {{0xaeac2b, 0x2}, {0xa7ad60, 0xc0001ab1d0}})
        /Open-IM-Server/src/Open-IM-SDK-Core/open_im_sdk/conversation_msg.go:205 +0x3ad
open_im_sdk/open_im_sdk.(*UserRelated).work(0xc0003ca2f0, {{0xaeac2b, 0x1}, {0xa7ad60, 0xc0001ab1d0}})
```

**Comment by MichealJl** [comment]
我也碰到了 同样的问题 ，  Open-IM-Server/src/Open-IM-SDK-Core/open_im_sdk/data_model这个文件里有个建表语句  创建一下就好了

**Comment by skiffer-git** [comment]
fixed
